#:schema https://mise.jdx.dev/schema/mise.json

[tasks]
  [tasks.dev]
  run = "tsdown --watch --no-clean"

  [tasks.build]
  wait_for = [
    "//projects/shared:build",
    "//projects/db:build",
  ]
  run = "tsdown"
  env = { NODE_ENV = "production" }

  [tasks.lint]
  wait_for = [ "//projects/shared:build" ]
  run = "tsc --noEmit"

  [tasks.deploy]
  depends = [ "build" ]
  run = "wrangler deploy"

[env]
_.path = "./node_modules/.bin"
