#:schema https://mise.jdx.dev/schema/mise.json

[tasks]
  [tasks.dev]
  depends = [ "sync" ]
  run = "next dev --inspect"

  [tasks.preview]
  depends = [ "build" ]
  run = "opennextjs-cloudflare preview"

  [tasks.build]
  depends = [ "sync" ]
  run = [
    "wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts",
    "next build",
    "opennextjs-cloudflare build --skipBuild",
  ]
  env = { NODE_ENV = "production" }

  [tasks.lint]
  depends = [ "sync" ]
  run = "tsc --noEmit"

  [tasks.fix]
  depends = [ "sync" ]
  run = "prisma format"

  # TODO disabled until GA
  #[tasks.publish]
  #run = "npm publish --access public --non-interactive"

  [tasks.sync]
  run = [{ tasks = [ "sync:*" ]}]

  [tasks.setup]
  run = [{ tasks = [ "setup:*" ]}]
  depends_post = "sync"

  [tasks.deploy]
  description = "Deploy to production"
  run = "opennextjs-cloudflare deploy"

  [tasks.upload]
  description = "Deploy to preview"
  run = "opennextjs-cloudflare upload"

[env]
_.path = "./node_modules/.bin"
